
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web_Push_Management.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Subscriber
{

    public int ID { get; set; }

    public string Name { get; set; }

    public string PrivateKey { get; set; }

    public string PublicKey { get; set; }

    public string Header { get; set; }

    public string Message { get; set; }

    public string URL { get; set; }

    public string Endpoint { get; set; }

}

}
