

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web_Push_Management.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Push_Notification_SystemEntities : DbContext
{
    public Push_Notification_SystemEntities()
        : base("name=Push_Notification_SystemEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }

    public virtual DbSet<Subscriber> Subscribers { get; set; }

    public virtual DbSet<SubscriberData> SubscriberDatas { get; set; }

}

}

